@startuml
object "student : Student\n(nazwa: Janek,\nmotywacja: 100)" as student
object "plan : Plan\n(dni: 15)" as plan
object "subject1 : Subject\n(nazwa: Matematyka,\nects: 6,\npredyspozycje: 70)" as math
object "subject2 : Subject\n(nazwa: Programowanie,\nects: 4,\npredyspozycje: 50)" as prog
object "sorter : SubjectSorter" as sorter
object "event1 : StudyEvent\n(Mat. 2h, dzień 1)" as event1
object "event2 : StudyEvent\n(Prog. 3h, dzień 2)" as event2
object "break : CoffeeBreak" as break
object "procrast : Procrastination" as procrast
object "result1 : ExamResult\n(Mat., score: 80, passed: true)" as result1
object "result2 : ExamResult\n(Prog., score: 55, passed: true)" as result2
object "visualizer : Visualizer" as visualizer
object "reader : Reader" as reader

student --> plan : posiada plan
student --> math : uczy się
student --> prog : uczy się
student --> event1 : historia
student --> event2 : historia
student --> break : stosuje motywator
student --> procrast : stosuje motywator
student --> visualizer
student --> reader
plan --> math : planuje naukę
plan --> prog : planuje naukę
sorter --> plan : sortowanie
plan --> sorter : pobiera przedmioty
result1 --> math : wynik z
result2 --> prog : wynik z

@enduml