@startuml

[*] --> Przygotowanie

Przygotowanie --> Sortowanie : subjects != null
Sortowanie --> Planowanie : plan == null
Planowanie --> Nauka : dzień = 1

Nauka --> MotywacjaSpada : motivation < próg
MotywacjaSpada --> Nauka : motywacja > próg

Nauka --> Egzamin : dzień > max
Egzamin --> Wyniki : exams taken
Wyniki --> [*]

@enduml