@startuml
[*] --> WprowadzanieDanych

WprowadzanieDanych --> GotowyDoNauki : dane poprawne
WprowadzanieDanych --> [*] : anuluj

GotowyDoNauki --> Nauka : rozpocznij naukę

state Nauka {
    [*] --> NaukaGodzina
    NaukaGodzina --> LosowanieMotywatora : zakończono godzinę nauki
    LosowanieMotywatora --> ZmieńMotywacje : [25% szans] trafia motywator
    LosowanieMotywatora --> NaukaGodzina : [75% szans] brak motywatora
    ZmieńMotywacje --> NaukaGodzina : zwiększono motywację
    NaukaGodzina --> KoniecNauki : koniec planu nauki
}

Nauka --> Sesja : koniec planu nauki
Sesja --> Egzamin : podejdź do egzaminu
Egzamin --> Wyniki : sprawdź wynik
Wyniki --> [*] : zakończ symulację

@enduml